config/routes.rb
Buscador::Application.routes.draw do
  resources :routes
  resources :items

  root :to => "routes#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :route, :dependent => :destroy
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.xml
  def index
    @items = Item.find(:all, :order => :route_id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    

  end

  # POST /items
  # POST /items.xml
  def create
    
    
    @item = Item.new( :logradouro => endereco[0], 
                      :endereco => endereco[1], 
                      :bairro => endereco[2],
                      :estado => endereco[3],
                      :cidade => endereco[4],
                      :cep => endereco[5],
                      :route_id => params[:item][:route_id]
                      )

    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/routes_controller.rb
#encoding: utf-8
class RoutesController < ApplicationController
  # GET /routes
  # GET /routes.xml
  def index
    @routes = Route.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @routes }
    end
  end

  # GET /routes/1
  # GET /routes/1.xml
  def show
    @route = Route.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/new
  # GET /routes/new.xml
  def new
    @route = Route.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/1/edit
  def edit
    @route = Route.find(params[:id])
  end

  # POST /routes
  # POST /routes.xml
  def create
    @route = Route.new(params[:route])

    respond_to do |format|
      if @route.save
        format.html { redirect_to(@route, :notice => 'Rota criada com sucesso.') }
        format.xml  { render :xml => @route, :status => :created, :location => @route }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /routes/1
  # PUT /routes/1.xml
  def update
    @route = Route.find(params[:id])

    respond_to do |format|
      if @route.update_attributes(params[:route])
        format.html { redirect_to(@route, :notice => 'Route was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.xml
  def destroy
    @route = Route.find(params[:id])
    @route.destroy

    respond_to do |format|
      format.html { redirect_to(routes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <div class = "field">
  <%= f.label :cep %>
  <p><%= f.text_field :cep %></p>

  <div class = "field" >
  <%= f.label :route_id, "Rota" %>
  <p><%= f.select :route_id, Route.all.collect { |r| [ r.nome, r.id ] }, :selected => params[:route]  %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>


<table>
  <tr>
    <th>Rota</th>
    <th>Logradouro</th>
    <th>Endereco</th>
    <th>Bairro</th>
    <th>Cidade</th>
    <th>Estado</th>
    <th>Cep</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.route.nome %></td>
    <td><%= item.logradouro %></td>
    <td><%= item.endereco %></td>
    <td><%= item.bairro %></td>
    <td><%= item.cidade %></td>
    <td><%= item.estado %></td>
    <td><%= item.cep %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Ver rotas', routes_path %>
<%= link_to 'Adicionar CEP', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Criar Nova Rota', :controller => :routes, :action => :new %>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p> 
  <b>Rota:</b>
  <%= @item.route.nome %>
</p>
  
<p>
  <b>Cep:</b>
  <%= @item.cep %>
</p>

<p>
  <b>Logradouro:</b>
  <%= @item.logradouro %>
</p>

<p>
  <b>Endereco:</b>
  <%= @item.endereco %>
</p>

<p>
  <b>Bairro:</b>
  <%= @item.bairro %>
</p>

<p>
  <b>Cidade:</b>
  <%= @item.cidade %>
</p>

<p>
  <b>Estado:</b>
  <%= @item.estado %>
</p>



<%= link_to 'Adicionar Outro CEP', :action => :new, :route => @item.route.id  %> |
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buscador</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Destinos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @routes.each do |route| %>
  <tr>
    <td><%= route.nome %></td>
    <td><%= route.items.count%> </td>
    <td><%= link_to 'Show', route %></td>
    <td><%= link_to 'Edit', edit_route_path(route) %></td>
    <td><%= link_to 'Destroy', route, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novos CEPs', items_path %>
<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<% @route.items.each_index do |x| %>
  <p><%= x+1 %>. 
     <%=link_to @route.items[x].cep, @route.items[x] %>, 
     <%= @route.items[x].cidade %>-
     <%= @route.items[x].estado %></p>
<% end %>

<%= link_to "Adicionar CEP", :controller => :items, :action => :new, :route =>  @route %> |
<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>